### PR TITLE
Dtds to hell

### PR DESCRIPTION
**Pull request by marcauberer**
Added dtd files for xml validation.

### CODE REVIEW

**Comment by marcauberer** [comment]
@Ordinateur-Hack is this ready to merge?

**Comment by marcauberer** [comment]
Btw it's not that easy to realize that perk you wanted (https://stackoverflow.com/questions/29845416/add-dtd-when-serializing-with-jackson-xmlmapper). We could work with string concatination in the backend, which really does not contribute to our clean and tidy code style (if you know what I mean ;)). I would suggest that we discuss in the next meeting, how to proceed with that issue.

**Comment by marcauberer** [comment]
Please also remove the example xmls before merging

**Comment by Splines** [comment]
@marcauberer Why should I remove the example xmls before merging? I created them, so that Mr. Roethig does not have to set a bunch of breakpoints on the website to see how the temporarily constructed XML-files (see JS code) look like.

**Comment by marcauberer** [comment]
Okay, agreed. But could you then please move the example xmls to a separate directory for better overview?

**Comment by Splines** [comment]
Do NOT merge yet, I've just found out that the new code contains some bugs... Will fix that soon.

**Review by kellerfisch — APPROVED** [review]

**Pull request merged**
