### PR TITLE
Styling improvements

### PR DESCRIPTION
**Pull request by marcauberer**
- Improved search bar style
- Improved detail view style
- Improved call list style

### CODE REVIEW

**Review by kellerfisch — COMMENTED** [review]
Needs some more changes. Not ready for merge yet.

**Comment by marcauberer** [comment]
Take your time and merge it as soon as you want to. It's only a draft pr.

**Comment by marcauberer** [comment]
Please refresh git with the gitignore file before merging, because the .idea folder, which is actually ignored got uploaded to GH.

**Comment by kellerfisch** [comment]
Ready for merge now

**Pull request merged**
